name: modelscope-fantom
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - pip=24.0
  - nvidia::cudatoolkit=11.5.0
  - cudnn=8.9
  - nvidia::cuda-nvcc=12.1
  - pip:
      # 魔搭社区核心依赖
      - modelscope
      - torch==2.3.1  # 与魔搭环境版本对齐
      - torchvision==0.18.1
      - torchaudio==2.3.1
      - transformers==4.41.0
      - accelerate==0.24.0
      - sentence-transformers==2.7.0
      - tokenizers==0.19
      - protobuf==3.20.3
      - pandas
      - tqdm==4.66.2
      - evaluate==0.4.2
      - requests==2.32.3
      - colorful==0.5.6
      - scikit-learn
      # 其他依赖保持与原始代码兼容
      - openai>=1.30.2
      - datasets==2.19.1
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-nvrtc-cu12==12.1.105
